
POST http://localhost:3000/api/ticket
Content-Type: application/json

{    
  "name":"Sem internet",
  "description":"Estamo sem internet desde as 18 horas",
  "type":"INICIADO",

}
###
PATCH  http://localhost:3000/api/ticket/3
Content-Type: application/json

{     
    "title": "internet ruim",
    "subTitle": "Internet ficou lenta derrepente",
    "description": "estava pulando corda e rebentou o cabo",
    "observacao": "observando",
    "status": "CONCLUIDO",
    "prioridade": "ALTA",
    "tecnicoId": null,
    "empresaId": 2,
    "categoriaId": null    
}
###
GET http://localhost:3000/api/ticket
Content-Type: application/json

###

###
DELETE  http://localhost:3000/api/ticket/2
Content-Type: application/json

###

###
GET http://localhost:3000/api/cliente
Content-Type: application/json

###
###
POST http://localhost:3000/api/cliente
Content-Type: application/json

  {
      "name":"Giga",
      "description":"Empresa do seguimento de telecomunicaçoes",
      "type":"Telecom" 
  }
###

###
DELETE  http://localhost:3000/api/cliente/1
Content-Type: application/json

###
POST http://localhost:3000/api/ticketRoadMap
Content-Type: application/json

  {
    "ticketId":77,
    "name": "INICIADO",
    "className": "bg-blue-500",
    "message": "Alterado"
  }
###
###
GET http://localhost:3000/api/ticketRoadMap
Content-Type: application/json

###

